### ISSUE TITLE
problems with groups

### ISSUE THREAD

**Issue by VinushsYT** [UserR00T/BP-Essentials#11]
Hello, I have a problem with the groups I have everything well programmed but I can not use them ingame

https://gyazo.com/71c0829876f4d76cc0d045a32a7474b8

**Comment by UserR00T** [comment]
Can you send the file as an attachment, please?

**Comment by VinushsYT** [comment]
[Essentials.ZIP](https://github.com/UserR00T/BP-Essentials/files/2303422/Essentials.ZIP)

**Comment by UserR00T** [comment]
So what doesn't work exactly?

**Comment by UserR00T** [comment]
Did you reload the server?

**Comment by UserR00T** [comment]
Closed due to inactivity.
