### ISSUE TITLE
essentials_settings - Whitelisted Jobs

### ISSUE THREAD

**Issue by 109117ca** [UserR00T/BP-Essentials#13]
Version: any.

Info:
i can even add only ONE Job. More will crash the point "WhitelistedJobs".

>  "WhitelistedJobs": [
  {
        "JobIndex": 12, 
		"Whitelisted": "jobindex:3, group:VIP"
  }],

I cant add anythin with "," or even in the same part.
Maybe its a bug or maybe a bad "tutorial" as comment.

**Comment by UserR00T** [comment]
Just tested it and worked fine, closing.

**Comment by 109117ca** [comment]
Maybe u can show me your config file for Whitelisted Jobs and i can find my exception.
