### ISSUE TITLE
[Bug] Free Command not working 2.6.4

### ISSUE THREAD

**Issue by masterfranky** [UserR00T/BP-Essentials#18]
/free command is not working. It gives the message "Freed player" but is not actually doing the command.

**Comment by masterfranky** [comment]
also the /sj command (set job) is not working either

**Comment by UserR00T** [comment]
Yup all known **game** issues. I cannot do anything against them, though nong will provide us with an patch for 0.94 to fix said problems.

**Comment by UserR00T** [comment]
Fixed in latest [release](https://github.com/UserR00T/BP-Essentials/releases/tag/v2.6.5). Closing.
