### ISSUE TITLE
[Bug] /setjob on another player changes your own Job

### ISSUE THREAD

**Issue by PLASMAchicken** [UserR00T/BP-Essentials#20]
Most likely because: https://github.com/UserR00T/BP-Essentials/blob/cffbb8a6d6771b5e5f7dc3bcd42846611d8bafd9/source/BP-Essentials/Chat/Commands/Admin/_SetJob.cs#L42-L49
should be `currPlayer.`

**Comment by UserR00T** [comment]
Known issue and will be fixed in the next update. I have some other things planned for the next update, which is why it's taking so long.

**Comment by UserR00T** [comment]
Fixed in latest release.
