### ISSUE TITLE
settings.json resets itself

### ISSUE THREAD

**Issue by iCromix** [UserR00T/BP-Essentials#23]
Hi, i'm having an issue with my server using BP-Essentials (2.6.6)

I configured the settings.json inside the "Essentials" folder, it worked fine until now, every time that i open my server, the settings.json file gets renamed to "settings.json.2019_46_24_04_46_39.OLD" and a new files replaces it, which is the default one. I didn't change any config, it broke itself... i think?

It's very frustrating because, i can't configure my server, the configuration just resets :(
Thanks in advice!
Cheers!

Edit: I found the issue, but still can't work it out, i added a custom group, it works in game (The player that i set gets the "role") the problem comes when i configure the group to execute comands this way:
![image](https://user-images.githubusercontent.com/53254094/61784556-4b5a4f00-ade0-11e9-8d7c-2e4003788393.png)
Then, the configuration resets.
I'm doing something wrong?

**Comment by Tatitooo** [comment]
Yes, you are doing something wrong, first that's not how JSON works, "ExecutableBy" isn't coded as an array of strings, if it were coded like a array of strings it would show like this:
![image](https://user-images.githubusercontent.com/23179501/61834431-4e8c2400-ae4e-11e9-95c7-569fcb99b65f.png)
Instead, it is a string, so when it's downloaded it shows like this:
![image](https://user-images.githubusercontent.com/23179501/61834483-8004ef80-ae4e-11e9-9159-147f3dae076f.png)
Essentials would read your text and then convert it to a array of strings, being separated by commas. (there's a explanation in the settings.json file)
Removing 2 quotes from the line that you had marked would fix your problem.
![image](https://user-images.githubusercontent.com/23179501/61834596-f144a280-ae4e-11e9-9cd9-3372522a9f0f.png)

**Comment by iCromix** [comment]
> Yes, you are doing something wrong, first that's not how JSON works, "ExecutableBy" isn't coded as an array of strings, if it were coded like a array of strings it would show like this:
> ![image](https://user-images.githubusercontent.com/23179501/61834431-4e8c2400-ae4e-11e9-95c7-569fcb99b65f.png)
> Instead, it is a string, so when it's downloaded it shows like this:
> ![image](https://user-images.githubusercontent.com/23179501/61834483-8004ef80-ae4e-11e9-9159-147f3dae076f.png)
> Essentials would read your text and then convert it to a array of strings, being separated by commas. (there's a explanation in the settings.json file)
> Removing 2 quotes from the line that you had marked would fix your problem.
> ![image](https://user-images.githubusercontent.com/23179501/61834596-f144a280-ae4e-11e9-9cd9-3372522a9f0f.png)

Thanks! It is fixed now!

**Comment by UserR00T** [comment]
Yes in BPE 3.0 this will be an actual string array. Thank you for helping him out, @Tatitooo.
