### ISSUE TITLE
[Suggestion] /who 

### ISSUE THREAD

**Issue by Kagemd** [UserR00T/BP-Essentials#3]
I know it's a work in progress but I would like to suggest the following

Admin Command(s)
!who <NAME>
 - Shows admins of the server information regarding the player. Job title, is very important for some servers and highly recommended.

!slay <NAME>
 - The ability to kill a player.

Not sure how functional this last one would be but
!strip <NAME>
 - Removes the clothing from a player. Purpose would be so players don't confuse somebody dressing up as a cop vs a real cop.

**Comment by UserR00T** [comment]
All commands have been added to BP-Essentials, thanks for suggesting!
