### ISSUE TITLE
New update not working

### ISSUE THREAD

**Issue by masterfranky** [UserR00T/BP-Essentials#9]
on update 2.4.4 commands are not working for groups
I have placed the command string in every possible way for my group to have certain permissions but when using the command it will always say no perms. I did have them working just fine on the previous version but now they wont work.

Examples of trying to make it work:
"ExecutableBy": "group:MOD, admins",
"ExecutableBy": "admins", "group:MOD",
"ExecutableBy": "admins", group:MOD,
"ExecutableBy": "admins, group:MOD"
"ExecutableBy": "admins", 'group:MOD',
none of them work. I have re-downloaded and installed the game and the plugin and still nothing.
----------
Also announcements are spamming every 10 seconds and will continue to do so even changing the number of seconds higher.

**Comment by UserR00T** [comment]
I've tried this feature on version ``2.4.4`` and it worked fine. Can you please send me your ``essentials_settings.txt`` and ``CustomGroups.txt``?

You can also find me on discord, I suggest using that because its easier to communicate that way. My discord is ``UserR00T#5907``

**Comment by masterfranky** [comment]
[essentials_settings.txt](https://github.com/UserR00T/BP-Essentials/files/2125710/essentials_settings.txt)
[CustomGroups.txt](https://github.com/UserR00T/BP-Essentials/files/2125711/CustomGroups.txt)

Yes some permissions are going to be different and wrong for the purpose of me trying every way I could think of to make it work. The groups one works fine. Also couldn't find you searching on disc.

**Comment by UserR00T** [comment]
Sorry for the very late response, forgot to check github issues. Could you send me your discord name+tag if you still need help?

**Comment by UserR00T** [comment]
Closed due to inactivity.
